apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-inventory-orchestrator
  namespace: inventory
  labels:
    app: inventory
    component: orchestrator
    cloud: aws
spec:
  schedule: $(CRON_SCHEDULE)
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: inventory
            component: orchestrator
            cloud: aws
        spec:
          serviceAccountName: aws-inventory-orchestrator-sa
          containers:
            - image: dfdsdk/aws-inventory-orchestrator:latest
              imagePullPolicy: Always
              name: orchestrator
              args:
                - $(INCLUDE_ACCOUNTS)
                - $(BUCKET_NAME)
              env:
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: MY_POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
          restartPolicy: OnFailure
